# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

deal_hand_cpp <- function(deck, n = 1L) {
    .Call(`_blackjack_deal_hand_cpp`, deck, n)
}

